### ISSUE TITLE
Refactor cellar chart to display TVL

### ISSUE THREAD

**Issue by xanderjl** [strangelove-ventures/sommelier#189]
Related to #51

Currently:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/25848639/167216713-dc2be6fd-5401-4de1-803a-ef974dfecd84.png">

Needs to be:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/25848639/165646849-1b6ea7b9-2474-4ea4-acd9-3f5426b7f3db.png">

## Tasks
- [ ] Write gql queries to pull in hourly, weekly, and all-time data for tvl (need clarity if this is `tvlActive` or `tvlTotal` @sandbochs)
- [ ] Run `yarn generate` to create hooks to pull in this data client-side (see [gql codegen section of README](https://github.com/strangelove-ventures/sommelier/blob/main/README.md#graphql-codegen) for more detail as to how this flow works)
- [ ] Pass data from these hooks to the Nivo chart depending on which value is currently selected, (24H, 1W, All Time)

## Resources
- [Nivo line charts](https://nivo.rocks/line/)
- [Subgraph playground](https://api.thegraph.com/subgraphs/name/elkdao/cellars/graphql)
